server.port=8081
mcp.server.url=http://localhost:8082
gemini.api.key=AIzaSyA6waq2jQSuEzjgcbZKY_kGnNURiQPJwVM
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent